version: '3.8'

services:
  terasim_service:
    build:
      context: .
      dockerfile: Dockerfile.cosim
    image: terasim-service:cosim
    container_name: terasim_service
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
      - HOME=/tmp
    volumes:
      - ./examples:/app/examples
      - ./outputs:/app/outputs
    command: ["/bin/bash", "/app/examples/scripts/main_cosim.sh"]

  # mcity_carla:
  #   image: public.ecr.aws/x0u0p9b6/mcity-digital-twin:0.9.15
  #   container_name: mcity_carla
  #   privileged: true
  #   network_mode: host
  #   environment:
  #     - DISPLAY=
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]
  #   command: ["/bin/bash", "./CarlaUE4.sh", "-RenderOffScreen"]
