# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from terasim_service.direct import cosim_direct_pb2 as terasim__service_dot_direct_dot_cosim__direct__pb2


class CosimDirectStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Tick = channel.unary_unary(
                '/terasim.cosim.direct.CosimDirect/Tick',
                request_serializer=terasim__service_dot_direct_dot_cosim__direct__pb2.TickRequest.SerializeToString,
                response_deserializer=terasim__service_dot_direct_dot_cosim__direct__pb2.TickResponse.FromString,
                )
        self.GetState = channel.unary_unary(
                '/terasim.cosim.direct.CosimDirect/GetState',
                request_serializer=terasim__service_dot_direct_dot_cosim__direct__pb2.GetStateRequest.SerializeToString,
                response_deserializer=terasim__service_dot_direct_dot_cosim__direct__pb2.TickResponse.FromString,
                )
        self.Stop = channel.unary_unary(
                '/terasim.cosim.direct.CosimDirect/Stop',
                request_serializer=terasim__service_dot_direct_dot_cosim__direct__pb2.StopRequest.SerializeToString,
                response_deserializer=terasim__service_dot_direct_dot_cosim__direct__pb2.StopResponse.FromString,
                )


class CosimDirectServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Tick(self, request, context):
        """Run exactly one SUMO step with the given agent commands applied before
        the step. Blocks until the step completes; returns the post-step state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Return the latest state without advancing the simulation
        (used for startup readiness checks and measurements).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Ask the simulation to stop after the current loop iteration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CosimDirectServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Tick': grpc.unary_unary_rpc_method_handler(
                    servicer.Tick,
                    request_deserializer=terasim__service_dot_direct_dot_cosim__direct__pb2.TickRequest.FromString,
                    response_serializer=terasim__service_dot_direct_dot_cosim__direct__pb2.TickResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=terasim__service_dot_direct_dot_cosim__direct__pb2.GetStateRequest.FromString,
                    response_serializer=terasim__service_dot_direct_dot_cosim__direct__pb2.TickResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=terasim__service_dot_direct_dot_cosim__direct__pb2.StopRequest.FromString,
                    response_serializer=terasim__service_dot_direct_dot_cosim__direct__pb2.StopResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'terasim.cosim.direct.CosimDirect', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CosimDirect(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Tick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/terasim.cosim.direct.CosimDirect/Tick',
            terasim__service_dot_direct_dot_cosim__direct__pb2.TickRequest.SerializeToString,
            terasim__service_dot_direct_dot_cosim__direct__pb2.TickResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/terasim.cosim.direct.CosimDirect/GetState',
            terasim__service_dot_direct_dot_cosim__direct__pb2.GetStateRequest.SerializeToString,
            terasim__service_dot_direct_dot_cosim__direct__pb2.TickResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/terasim.cosim.direct.CosimDirect/Stop',
            terasim__service_dot_direct_dot_cosim__direct__pb2.StopRequest.SerializeToString,
            terasim__service_dot_direct_dot_cosim__direct__pb2.StopResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
