# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: terasim_service/direct/cosim_direct.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)terasim_service/direct/cosim_direct.proto\x12\x14terasim.cosim.direct\"]\n\x0c\x41gentCommand\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x12\n\nagent_type\x18\x02 \x01(\t\x12\x14\n\x0c\x63ommand_type\x18\x03 \x01(\t\x12\x11\n\tdata_json\x18\x04 \x01(\t\"C\n\x0bTickRequest\x12\x34\n\x08\x63ommands\x18\x01 \x03(\x0b\x32\".terasim.cosim.direct.AgentCommand\"\x11\n\x0fGetStateRequest\"\r\n\x0bStopRequest\"\x1a\n\x0cStopResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"m\n\x0cTickResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nstate_json\x18\x02 \x01(\t\x12\x1b\n\x13\x63ompleted_sumo_time\x18\x03 \x01(\x01\x12\x1c\n\x14\x63ompleted_tick_count\x18\x04 \x01(\x03\x32\x82\x02\n\x0b\x43osimDirect\x12M\n\x04Tick\x12!.terasim.cosim.direct.TickRequest\x1a\".terasim.cosim.direct.TickResponse\x12U\n\x08GetState\x12%.terasim.cosim.direct.GetStateRequest\x1a\".terasim.cosim.direct.TickResponse\x12M\n\x04Stop\x12!.terasim.cosim.direct.StopRequest\x1a\".terasim.cosim.direct.StopResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'terasim_service.direct.cosim_direct_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AGENTCOMMAND']._serialized_start=67
  _globals['_AGENTCOMMAND']._serialized_end=160
  _globals['_TICKREQUEST']._serialized_start=162
  _globals['_TICKREQUEST']._serialized_end=229
  _globals['_GETSTATEREQUEST']._serialized_start=231
  _globals['_GETSTATEREQUEST']._serialized_end=248
  _globals['_STOPREQUEST']._serialized_start=250
  _globals['_STOPREQUEST']._serialized_end=263
  _globals['_STOPRESPONSE']._serialized_start=265
  _globals['_STOPRESPONSE']._serialized_end=291
  _globals['_TICKRESPONSE']._serialized_start=293
  _globals['_TICKRESPONSE']._serialized_end=402
  _globals['_COSIMDIRECT']._serialized_start=405
  _globals['_COSIMDIRECT']._serialized_end=663
# @@protoc_insertion_point(module_scope)
