#!/bin/bash
set -e

CARLA_PORT=${CARLA_PORT:-2010}
CARLA_HOST=${CARLA_HOST:-localhost}
CARLA_PACKAGE_MAP_NAME=${CARLA_PACKAGE_MAP_NAME:-odaibatest5}
TERASIM_CONFIG=${TERASIM_CONFIG:-/app/examples/scenarios/cosim_odaiba_ll2.yaml}
TERASIM_PORT=${TERASIM_PORT:-8000}
ENABLE_SUMO_GUI=${ENABLE_SUMO_GUI:-1}
SUMO_DISPLAY=${SUMO_DISPLAY:-:20}
SUMO_NOVNC_PORT=${SUMO_NOVNC_PORT:-6093}
SUMO_VNC_PORT=${SUMO_VNC_PORT:-5913}
VNC_PASSWORD=${VNC_PASSWORD:-headless}
SUMO_GUI_TRACK_VEHICLE=${SUMO_GUI_TRACK_VEHICLE:-AV}
SUMO_GUI_TRACK_ZOOM=${SUMO_GUI_TRACK_ZOOM:-3000}
CARLA_COSIM_MOTION_LOG=${CARLA_COSIM_MOTION_LOG:-}
CARLA_COSIM_DIAG_ROLE_NAMES=${CARLA_COSIM_DIAG_ROLE_NAMES:-AV}
CARLA_COSIM_DIAG_BACKWARD_THRESHOLD=${CARLA_COSIM_DIAG_BACKWARD_THRESHOLD:--0.05}
CARLA_COSIM_DIAG_MIN_MOVEMENT=${CARLA_COSIM_DIAG_MIN_MOVEMENT:-0.01}
CARLA_COSIM_PROFILE_LOG=${CARLA_COSIM_PROFILE_LOG:-}
CARLA_COSIM_PROFILE_PRINT_EVERY=${CARLA_COSIM_PROFILE_PRINT_EVERY:-20}
CARLA_COSIM_ACTOR_PROFILE_LOG=${CARLA_COSIM_ACTOR_PROFILE_LOG:-}
CARLA_COSIM_ACTOR_PROFILE_PRINT_EVERY=${CARLA_COSIM_ACTOR_PROFILE_PRINT_EVERY:-20}
CARLA_COSIM_SPAWN_FAILURE_BACKOFF_SECONDS=${CARLA_COSIM_SPAWN_FAILURE_BACKOFF_SECONDS:-5.0}
CARLA_COSIM_SPAWN_FAILURE_BACKOFF_MAX_SECONDS=${CARLA_COSIM_SPAWN_FAILURE_BACKOFF_MAX_SECONDS:-30.0}
CARLA_COSIM_SPAWN_Z_CLEARANCE=${CARLA_COSIM_SPAWN_Z_CLEARANCE:-5.0}
CARLA_COSIM_ACTOR_FILTER=${CARLA_COSIM_ACTOR_FILTER:-0}
CARLA_COSIM_ACTOR_FILTER_CENTER_ID=${CARLA_COSIM_ACTOR_FILTER_CENTER_ID:-AV}
CARLA_COSIM_ACTOR_FILTER_RADIUS=${CARLA_COSIM_ACTOR_FILTER_RADIUS:-300}

echo "Using CARLA host: ${CARLA_HOST}"
echo "Using CARLA port: ${CARLA_PORT}"
echo "Using packaged CARLA map: ${CARLA_PACKAGE_MAP_NAME}"
echo "Using TeraSim config: ${TERASIM_CONFIG}"
echo "Using TeraSim port: ${TERASIM_PORT}"
echo "Using SUMO GUI/noVNC: ${ENABLE_SUMO_GUI}"
echo "Using SUMO noVNC port: ${SUMO_NOVNC_PORT}"
echo "Using SUMO GUI track vehicle: ${SUMO_GUI_TRACK_VEHICLE}"
echo "Using SUMO GUI track zoom: ${SUMO_GUI_TRACK_ZOOM}"
if [ -n "${CARLA_COSIM_MOTION_LOG}" ]; then
    echo "Using CARLA co-sim motion log: ${CARLA_COSIM_MOTION_LOG}"
    echo "Using CARLA co-sim diagnostic roles: ${CARLA_COSIM_DIAG_ROLE_NAMES}"
fi
if [ -n "${CARLA_COSIM_PROFILE_LOG}" ]; then
    echo "Using CARLA co-sim profile log: ${CARLA_COSIM_PROFILE_LOG}"
fi
if [ -n "${CARLA_COSIM_ACTOR_PROFILE_LOG}" ]; then
    echo "Using CARLA co-sim actor profile log: ${CARLA_COSIM_ACTOR_PROFILE_LOG}"
fi
echo "Using CARLA co-sim spawn failure backoff: ${CARLA_COSIM_SPAWN_FAILURE_BACKOFF_SECONDS}s"
echo "Using CARLA co-sim spawn failure max backoff: ${CARLA_COSIM_SPAWN_FAILURE_BACKOFF_MAX_SECONDS}s"
echo "Using CARLA co-sim spawn Z clearance: ${CARLA_COSIM_SPAWN_Z_CLEARANCE}m"
if [ "${CARLA_COSIM_ACTOR_FILTER}" != "0" ]; then
    echo "Using CARLA co-sim actor filter: center=${CARLA_COSIM_ACTOR_FILTER_CENTER_ID} radius=${CARLA_COSIM_ACTOR_FILTER_RADIUS}m"
fi

exec docker compose -f docker-compose.cosim-odaiba-ll2.yml run --rm \
    -e CARLA_HOST="${CARLA_HOST}" \
    -e CARLA_PORT="${CARLA_PORT}" \
    -e CARLA_PACKAGE_MAP_NAME="${CARLA_PACKAGE_MAP_NAME}" \
    -e TERASIM_CONFIG="${TERASIM_CONFIG}" \
    -e TERASIM_PORT="${TERASIM_PORT}" \
    -e ENABLE_SUMO_GUI="${ENABLE_SUMO_GUI}" \
    -e SUMO_DISPLAY="${SUMO_DISPLAY}" \
    -e SUMO_NOVNC_PORT="${SUMO_NOVNC_PORT}" \
    -e SUMO_VNC_PORT="${SUMO_VNC_PORT}" \
    -e VNC_PASSWORD="${VNC_PASSWORD}" \
    -e SUMO_GUI_TRACK_VEHICLE="${SUMO_GUI_TRACK_VEHICLE}" \
    -e SUMO_GUI_TRACK_ZOOM="${SUMO_GUI_TRACK_ZOOM}" \
    -e CARLA_COSIM_MOTION_LOG="${CARLA_COSIM_MOTION_LOG}" \
    -e CARLA_COSIM_DIAG_ROLE_NAMES="${CARLA_COSIM_DIAG_ROLE_NAMES}" \
    -e CARLA_COSIM_DIAG_BACKWARD_THRESHOLD="${CARLA_COSIM_DIAG_BACKWARD_THRESHOLD}" \
    -e CARLA_COSIM_DIAG_MIN_MOVEMENT="${CARLA_COSIM_DIAG_MIN_MOVEMENT}" \
    -e CARLA_COSIM_PROFILE_LOG="${CARLA_COSIM_PROFILE_LOG}" \
    -e CARLA_COSIM_PROFILE_PRINT_EVERY="${CARLA_COSIM_PROFILE_PRINT_EVERY}" \
    -e CARLA_COSIM_ACTOR_PROFILE_LOG="${CARLA_COSIM_ACTOR_PROFILE_LOG}" \
    -e CARLA_COSIM_ACTOR_PROFILE_PRINT_EVERY="${CARLA_COSIM_ACTOR_PROFILE_PRINT_EVERY}" \
    -e CARLA_COSIM_BATCH_TRANSFORM="${CARLA_COSIM_BATCH_TRANSFORM:-0}" \
    -e CARLA_COSIM_BATCH_SPAWN="${CARLA_COSIM_BATCH_SPAWN:-0}" \
    -e CARLA_COSIM_ACTOR_FILTER="${CARLA_COSIM_ACTOR_FILTER}" \
    -e CARLA_COSIM_ACTOR_FILTER_CENTER_ID="${CARLA_COSIM_ACTOR_FILTER_CENTER_ID}" \
    -e CARLA_COSIM_ACTOR_FILTER_RADIUS="${CARLA_COSIM_ACTOR_FILTER_RADIUS}" \
    -e CARLA_COSIM_SPAWN_Z_CLEARANCE="${CARLA_COSIM_SPAWN_Z_CLEARANCE}" \
    -e CARLA_COSIM_SPAWN_FAILURE_BACKOFF_SECONDS="${CARLA_COSIM_SPAWN_FAILURE_BACKOFF_SECONDS}" \
    -e CARLA_COSIM_SPAWN_FAILURE_BACKOFF_MAX_SECONDS="${CARLA_COSIM_SPAWN_FAILURE_BACKOFF_MAX_SECONDS}" \
    terasim_service \
    /bin/bash /app/examples/scripts/main_cosim_odaiba_ll2_packaged.sh
