simulation_module: my_simulations
simulation_class: CarSimulation
parameters:
  num_cars: 100
  simulation_time: 3600
seed: 42
simulation_type: safetest_odaiba_ll2
output:
  dir: /app/outputs
  name: odaiba_ll2_generated_test
  nth: '0_0'
  aggregated_dir: aggregated
environment:
  module: terasim_nde_nade.envs
  class: NADEWithAV
  parameters:
    vehicle_factory: terasim_nde_nade.vehicle.nde_vehicle_factory.NDEVehicleFactory
    info_extractor: terasim.logger.infoextractor.InfoExtractor
    log_flag: true
    warmup_time_lb: 500
    warmup_time_ub: 520
    run_time: 600
    MOBIL_lc_flag: true
    stochastic_acc_flag: false
    sumo_net_file_path: /app/examples/maps/odaiba_ll2/network_0505.net.xml
    sumo_cfg_file_path: /app/examples/maps/odaiba_ll2/simulation.sumocfg
    drive_rule: righthand
    adversity_sampling_probability: 1.0
    adversity_cfg:
      vehicle:
        intersection_cutin:
          _target_: terasim_nde_nade.adversity.vehicles.lanechange_adversity.LanechangeAdversity
          _convert_: all
          location: intersection
          ego_type: vehicle
          probability: 0.01
          predicted_collision_type: intersection_cutin
        intersection_rearend_leader:
          _target_: terasim_nde_nade.adversity.vehicles.leader_adversity.LeaderAdversity
          _convert_: all
          location: intersection
          ego_type: vehicle
          probability: 0.01
          predicted_collision_type: intersection_rearend
        intersection_rearend_follower:
          _target_: terasim_nde_nade.adversity.vehicles.follower_adversity.FollowerAdversity
          _convert_: all
          location: intersection
          ego_type: vehicle
          probability: 0.01
          predicted_collision_type: intersection_rearend_follower
        intersection_tfl:
          _target_: terasim_nde_nade.adversity.vehicles.trafficrule_adversity.TrafficRuleAdversity
          _convert_: all
          location: intersection
          ego_type: vehicle
          probability: 0.01
          predicted_collision_type: intersection_tfl
        intersection_headon:
          _target_: terasim_nde_nade.adversity.vehicles.headon_adversity.HeadonAdversity
          _convert_: all
          location: intersection
          ego_type: vehicle
          probability: 0.01
          predicted_collision_type: intersection_headon
      vulnerable_road_user:
        jaywalking:
          _target_: terasim_nde_nade.adversity.vru.jaywalking_adversity.JaywalkingAdversity
          _convert_: all
          location: crosswalk
          ego_type: vulnerable_road_user
          probability: 0.01
          predicted_collision_type: intersection_jaywalking
    av_debug_control: true
    AV_cfg:
      type: NDE_URBAN
      cache_radius: 100
      control_radius: 50
      route:
      - edge_729
      - edge_730
      - edge_3228
      - edge_734
      - edge_836
      - edge_736
      - edge_839
      - edge_738
      - edge_830
      - edge_739
      - edge_740
      - edge_1380
      - edge_1146
      - edge_1033
      - edge_1389
      - edge_1072
      - edge_1077
      - edge_1120
      - edge_1124
      - edge_400
      - edge_417
      - edge_420
      - edge_426
      - edge_432
      - edge_427
      - edge_125
      - edge_127
      - edge_1317
      - edge_754
      - edge_467
      - edge_98
      - edge_99
      - edge_2475
      - edge_2480
      - edge_1597
      - edge_1591
      - edge_1586
      - edge_2095
      - edge_2094
      - edge_2092
      - edge_2164
      - edge_2177
      - edge_2089
      - edge_2101
      - edge_2102
      - edge_1605
      - edge_1603
simulator:
  module: terasim.simulator
  class: Simulator
  parameters:
    num_tries: 10
    gui_flag: false
    realtime_flag: false
    sumo_output_file_types:
    - fcd_all
    - collision
    - tripinfo
    traffic_scale: 1.0
input:
  sumo_net_file: /app/examples/maps/odaiba_ll2/network_0505.net.xml
  sumo_config_file: /app/examples/maps/odaiba_ll2/simulation.sumocfg
logging:
  levels:
  - TRACE
  - INFO
